### prueba
GET http://localhost:3000/api/


#################### USERS ####################

### Traer todos los users
GET http://localhost:3000/api/users


### Traer un usuario por id
GET http://localhost:3000/api/users/66917248627f264620d04731


### Crear un nuevo usuario
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "Pdnasdasjkdhkicar",
    "password": "contraseña",
    "email": "modidsakdhasjkrr@example.com",
    "firstname": "Nuevo",
    "lastname": "Usuario",
    "birthDate": "1990-01-01"
}

### Dar de baja un usuario
DELETE  http://localhost:3000/api/users/6691768e8f5ce1c4703621fc


### Mofidicar un usuario
PUT http://localhost:3000/api/users/modify/6696b70701fa827bf6bf6c7e
Content-Type: application/json

{
    "username": "Modificado"
}

### Traer usuarios por nombre de equipo
GET http://localhost:3000/api/users/team/Salado
Content-Type: application/json

#################### TEAMS ####################

### Crear un team
POST http://localhost:3000/api/teams
Content-Type: application/json

{
    "teamname": "Para modificar",
    "description": "a"
}

### Traer todos los teams
GET http://localhost:3000/api/teams


### Traer un team por id
GET http://localhost:3000/api/teams/6696b3905e856b1bd70ab5ff



### Dar de baja un team
DELETE  http://localhost:3000/api/teams/6695901b01d57aacc4a0b07a


### Modificar un team
PUT http://localhost:3000/api/teams/6696b3905e856b1bd70ab5ff
Content-Type: application/json

{
    "teamname": "Modificado",
    "description": "a"
}

### Asignar un team a un usuario
PUT http://localhost:3000/api/users/6691768e8f5ce1c4703621fc



#################### RESEÑAS ####################

### Subir una foto (no a la reseña)
POST http://localhost:3000/api/imgs
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="reviewId"

123
--boundary
Content-Disposition: form-data; name="file"; filename="dragon.jpg"
Content-Type: image/jpeg

< ./C:/Users/cami/Pictures/dragon.jpg
--boundary--



### Crear la reseña
POST http://localhost:3000/api/reviews
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="reviewDate"

2024-07-19
--boundary
Content-Disposition: form-data; name="reviewExperience"

Great coffee and ambiance!
--boundary
Content-Disposition: form-data; name="reviewPrice"

15
--boundary
Content-Disposition: form-data; name="amountPeople"

2
--boundary
Content-Disposition: form-data; name="consumedFood"

Cappuccino and Croissant
--boundary
Content-Disposition: form-data; name="attentionScore"

5
--boundary
Content-Disposition: form-data; name="placeScore"

4
--boundary
Content-Disposition: form-data; name="userId"

668da729a9fa3577de3460df
--boundary
Content-Disposition: form-data; name="photos"; filename="dragon.jpg"
Content-Type: image/jpeg

< ./C:/Users/cami/Pictures/dragon.jpg
--boundary
Content-Disposition: form-data; name="photos"; filename="perros.jpg"
Content-Type: image/jpeg

< ./C:/Users/cami/Pictures/perros.jpg

--boundary--
