### Traer todos los users
GET http://localhost:3000/api/users

### prueba
GET http://localhost:3000/api/

### Traer un usuario por id
GET http://localhost:3000/api/users/66917248627f264620d04731


### Crear un nuevo usuario
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "NUEVO2",
    "password": "contraseña",
    "email": "nuevo_usur2@example.com",
    "firstname": "Nuevo",
    "lastname": "Usuario",
    "birthDate": "1990-01-01"
}

### Dar de baja un usuario
DELETE  http://localhost:3000/api/users/6691768e8f5ce1c4703621fc

